import React, { useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import axios from "axios";
import { AI_ENGINE_URL } from "../lib/socket";

export default function ReportViewer({ reportMarkdown, patientName, sessionId }) {
  const [isExporting, setIsExporting] = useState(false);
  const [exportError, setExportError] = useState(null);

  async function handleExportPdf() {
    setIsExporting(true);
    setExportError(null);
    try {
      // 1. Try server endpoint first if available
      const response = await axios.post(
        `${AI_ENGINE_URL}/generate-pdf`,
        {
          report_markdown: reportMarkdown,
          patient_name: patientName,
          session_id: sessionId,
        },
        { responseType: "blob", timeout: 2500 }
      );

      const url = window.URL.createObjectURL(new Blob([response.data], { type: "application/pdf" }));
      const link = document.createElement("a");
      link.href = url;
      link.setAttribute("download", `CAT_Report_${patientName.replace(/\s+/g, "_")}.pdf`);
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.URL.revokeObjectURL(url);
    } catch (_) {
      // 2. Client-side Print to PDF engine fallback
      try {
        const printWindow = window.open("", "_blank");
        if (printWindow) {
          const reportContainer = document.querySelector(".max-h-\\[600px\\]");
          const reportContentHtml = reportContainer ? reportContainer.innerHTML : `<pre>${reportMarkdown}</pre>`;

          printWindow.document.write(`
            <!DOCTYPE html>
            <html>
              <head>
                <title>Clinical Assessment Report - ${patientName}</title>
                <style>
                  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; padding: 40px; color: #0f172a; line-height: 1.6; background: #fff; }
                  h1 { font-size: 22px; color: #1e1b4b; border-bottom: 2px solid #4f46e5; padding-bottom: 8px; margin-bottom: 12px; }
                  h2 { font-size: 16px; color: #4338ca; margin-top: 20px; margin-bottom: 8px; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; }
                  h3 { font-size: 14px; color: #334155; margin-top: 14px; margin-bottom: 6px; }
                  p, li { font-size: 13px; color: #334155; margin-bottom: 8px; }
                  table { width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 12px; }
                  th, td { border: 1px solid #cbd5e1; padding: 8px 10px; text-align: left; }
                  th { background-color: #f1f5f9; font-weight: bold; color: #1e293b; }
                  .header-bar { background-color: #f8fafc; border: 1px solid #e2e8f0; padding: 12px 16px; border-radius: 8px; margin-bottom: 20px; font-size: 12px; }
                  .footer { margin-top: 40px; font-size: 10px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 10px; text-align: center; }
                </style>
              </head>
              <body>
                <h1>Communication Assessment Tool (CAT) — Clinical Evaluation Report</h1>
                <div class="header-bar">
                  <strong>Patient:</strong> ${patientName} &nbsp;|&nbsp; <strong>Session ID:</strong> ${sessionId || "CAT-SESSION-01"} &nbsp;|&nbsp; <strong>Date:</strong> ${new Date().toLocaleDateString()}
                </div>
                <div>${reportContentHtml}</div>
                <div class="footer">Generated by CAT Platform — Confidential Speech-Language Pathology Assessment</div>
              </body>
            </html>
          `);
          printWindow.document.close();
          printWindow.focus();
          setTimeout(() => {
            printWindow.print();
            printWindow.close();
          }, 400);
        }
      } catch (e) {
        setExportError("Unable to open print window. Please use Ctrl+P to save as PDF.");
      }
    } finally {
      setIsExporting(false);
    }
  }

  if (!reportMarkdown) return null;

  return (
    <div className="bg-slate-900/90 rounded-xl border border-slate-800 overflow-hidden shadow-xl">
      <div className="flex items-center justify-between bg-slate-950/80 px-5 py-3 border-b border-slate-800">
        <div className="flex items-center gap-2">
          <span className="w-2.5 h-2.5 rounded-full bg-emerald-400" />
          <span className="text-xs font-bold text-slate-200 tracking-wide uppercase">AI Clinical Report Narrative</span>
        </div>

        <button
          onClick={handleExportPdf}
          disabled={isExporting}
          className="text-xs font-semibold px-4 py-2 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white disabled:opacity-40 transition shadow-md shadow-emerald-900/30 flex items-center gap-1.5"
        >
          {isExporting ? (
            <>
              <span className="w-3 h-3 rounded-full border-2 border-white border-t-transparent animate-spin" />
              <span>Exporting PDF...</span>
            </>
          ) : (
            <>
              <span>⬇ Download PDF Report</span>
            </>
          )}
        </button>
      </div>

      {exportError && (
        <div className="bg-rose-500/10 text-rose-300 text-xs px-4 py-2 border-b border-rose-500/20">
          {exportError}
        </div>
      )}

      <div className="p-6 max-h-[600px] overflow-y-auto font-sans text-slate-300 space-y-4 text-sm leading-relaxed">
        <ReactMarkdown
          remarkPlugins={[remarkGfm]}
          components={{
            h1: ({ node, ...props }) => <h1 className="text-2xl font-extrabold text-white pb-2 border-b border-slate-800 mb-4" {...props} />,
            h2: ({ node, ...props }) => <h2 className="text-lg font-bold text-indigo-300 mt-6 mb-3 border-b border-slate-800/80 pb-1" {...props} />,
            h3: ({ node, ...props }) => <h3 className="text-sm font-semibold text-slate-200 mt-4 mb-2" {...props} />,
            p: ({ node, ...props }) => <p className="text-slate-300 text-sm leading-relaxed mb-3" {...props} />,
            ul: ({ node, ...props }) => <ul className="list-disc list-inside space-y-1 text-slate-300 text-sm pl-2 mb-3" {...props} />,
            li: ({ node, ...props }) => <li className="text-slate-300 text-sm" {...props} />,
            strong: ({ node, ...props }) => <strong className="font-bold text-white" {...props} />,
            table: ({ node, ...props }) => (
              <div className="overflow-x-auto my-4 rounded-xl border border-slate-800 bg-slate-950/80 shadow-lg">
                <table className="w-full text-left border-collapse text-xs" {...props} />
              </div>
            ),
            thead: ({ node, ...props }) => <thead className="bg-slate-900/90 text-indigo-300 font-semibold border-b border-slate-800 uppercase tracking-wider text-[11px]" {...props} />,
            tbody: ({ node, ...props }) => <tbody className="divide-y divide-slate-800/60" {...props} />,
            tr: ({ node, ...props }) => <tr className="hover:bg-slate-900/50 transition-colors" {...props} />,
            th: ({ node, ...props }) => <th className="px-4 py-3 font-semibold text-indigo-200 border-r border-slate-800/60 last:border-r-0" {...props} />,
            td: ({ node, ...props }) => <td className="px-4 py-3 text-slate-300 border-r border-slate-800/40 last:border-r-0 leading-relaxed" {...props} />,
          }}
        >
          {reportMarkdown}
        </ReactMarkdown>
      </div>
    </div>
  );
}

